# Generated by Django 5.2.3 on 2025-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(default='piece', help_text='e.g., kg, dozen, piece, bag', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='product_images/')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this product has been approved by an admin to be publicly listed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'permissions': [('can_add_unapproved_product', 'Can add product (unapproved by default)'), ('can_approve_product', 'Can approve product for listing')],
            },
        ),
    ]
