# Generated by Django 5.2.3 on 2025-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration Verification'), ('password_reset', 'Password Reset Verification')], default='registration', max_length=20),
        ),
    ]
