"""
Django settings for farm_shop_project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'phonenumber_field',

    # Local apps
    'apps.core',
    'apps.users',
    'apps.products',
    'apps.orders',
    'apps.employees',
    'apps.farmers',
    'apps.businesses',
    'apps.dashboards',
    'apps.finance',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm_shop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm_shop_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static_root'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media_root'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# --- Email Settings (for OTP, employee credentials, password reset, birthday wishes) ---
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@farmshop.com')
SERVER_EMAIL = 'errors@farmshop.com'       # For Django error reporting


OTP_VALIDITY_MINUTES = 5

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

BIRTHDAY_WISH_HOUR = 10

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Jazzmin admin theme settings
JAZZMIN_SETTINGS = {
    "site_title": "R.S. Krishi Seva Kendra Admin",
    "site_header": "R.S. Krishi Seva Kendra",
    "site_brand": "Farm Shop",
    "site_logo": "admin/img/AdminLTELogo.png",
    "welcome_sign": "Welcome to R.S. Krishi Seva Kendra Admin",
    "copyright": "R.S. Krishi Seva Kendra",
    "search_model": ["auth.User", "products.Product"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"},
        {"app": "products"},
    ],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "icon": "fas fa-home"},
        {"name": "Admin Dashboard (UI)", "url": "users:admin_dashboard", "icon": "fas fa-users-cog"},
        {"name": "Django Admin Home", "url": "admin:index", "icon": "fas fa-cogs"},
        {"model": "auth.User"},
    ],
    "sidemenu_links": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt"},
        {"name": "Admin Dashboard (UI)", "url": "users:admin_dashboard", "icon": "fas fa-users-cog"},
        {"heading": "User Management"},
        {
            "name": "Add New Employee",
            "url": "users:admin_create_employee",
            "icon": "fas fa-user-plus",
            "permissions": ["auth.add_user"]
        },
        {
            "name": "All Users (Raw Admin)",
            "url": "admin:auth_user_changelist",
            "icon": "fas fa-users",
            "permissions": ["auth.view_user"]
        },
        {"app": "users", "icon": "fas fa-user-tag"},
        {"heading": "Shop Management"},
        {"app": "products", "icon": "fas fa-leaf"},
        {"app": "orders", "icon": "fas fa-shopping-cart"},
        {"app": "employees", "icon": "fas fa-briefcase"},
        {"app": "farmers", "icon": "fas fa-tractor"},
        {"app": "businesses", "icon": "fas fa-building"},
        {"app": "finance", "icon": "fas fa-file-invoice-dollar"}, # <--- NEW: Jazzmin icon for finance app
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "show_ui_builder": DEBUG,
    "order_with_respect_to": ["auth", "users", "products", "orders", "employees", "farmers", "businesses", "finance"], # <--- NEW: Add finance to order
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.CustomUser": "fas fa-user-circle",
        "users.OneTimePassword": "fas fa-key",
        "products.Product": "fas fa-apple-alt",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-box",
        "orders.OrderItem": "fas fa-box-open",
        "employees.Employee": "fas fa-id-badge",
        "farmers.Farmer": "fas fa-seedling",
        "businesses.Business": "fas fa-city",
        "dashboards.Dashboard": "fas fa-chart-line",
        "finance.FarmerBill": "fas fa-file-invoice", # <--- NEW: Icon for FarmerBill model
    },
    "related_modal_active": False
}

JAZZMIN_UI_SETTINGS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "navbar_fixed": True,
    "navbar_links_left": [],
    "navbar_links_right": [],
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "sidebar_show_quick_panel": False,
    "sidebar_show_tooltips": True,
    "sidebar_search": True,
    "show_breadcrumbs": True,
    "site_width": "full",
    "site_brand": "Farm Shop",
    "site_brand_header_link": "/",
    "welcome_text_header": "Farm Shop Admin",
    "topbar_brand_text": "Farm Shop",
    "custom_css": None,
    "custom_js": None,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'apps.users.views': { # Target the logger specifically in your views.py
            'handlers': ['console'],
            'level': 'DEBUG', # Always show DEBUG messages from your custom views
            'propagate': False,
        },
    },
}