"""
Django settings for farm_shop_project project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-shjkt5up9^qf!%_rknq0t+o3p^tr=f9inszbwi)&@umqd&kek('

DEBUG = True

print(f"Django DEBUG is currently: {DEBUG}")

ALLOWED_HOSTS = ['*'] # Allows all hosts for local development. In production, replace with your domain(s): ['yourdomain.com', 'www.yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'phonenumber_field',

    'apps.core',
    'apps.users',
    'apps.products',
    'apps.orders',
    'apps.employees',
    'apps.farmers',
    'apps.businesses',
    'apps.dashboards',
    'apps.finance', # <--- NEW APP
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm_shop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm_shop_project.wsgi.application'
ASGI_APPLICATION = 'farm_shop_project.asgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# --- Email Settings (for OTP, employee credentials, password reset, birthday wishes) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'ishantsingh01275@gmail.com'
EMAIL_HOST_PASSWORD = 'wrms alha oxsq cbaa'

DEFAULT_FROM_EMAIL = 'no-reply@farmshop.com' # Email address that appears as the sender
SERVER_EMAIL = 'errors@farmshop.com'       # For Django error reporting

if DEBUG and not all([EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD]):
    print("\nWARNING: Email settings are incomplete. Emails might not be sent. Please check your .env file.")

OTP_VALIDITY_MINUTES = 5

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

BIRTHDAY_WISH_HOUR = 10

# Twilio Settings (Commented out for now)
# TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
# TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')
# TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER')
# TWILIO_WHATSAPP_NUMBER = os.environ.get('TWILIO_WHATSAPP_NUMBER')


JAZZMIN_SETTINGS = {
    "site_title": "Farm Shop Admin",
    "site_header": "Farm Shop",
    "welcome_sign": "Welcome to the Farm Shop Admin Panel",
    "copyright": "Farm Shop Ltd.",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "icon": "fas fa-home"},
        {"name": "Admin Dashboard (UI)", "url": "users:admin_dashboard", "icon": "fas fa-users-cog"},
        {"name": "Django Admin Home", "url": "admin:index", "icon": "fas fa-cogs"},
        {"model": "auth.User"},
    ],
    "sidemenu_links": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt"},
        {"name": "Admin Dashboard (UI)", "url": "users:admin_dashboard", "icon": "fas fa-users-cog"},
        {"heading": "User Management"},
        {
            "name": "Add New Employee",
            "url": "users:admin_create_employee",
            "icon": "fas fa-user-plus",
            "permissions": ["auth.add_user"]
        },
        {
            "name": "All Users (Raw Admin)",
            "url": "admin:auth_user_changelist",
            "icon": "fas fa-users",
            "permissions": ["auth.view_user"]
        },
        {"app": "users", "icon": "fas fa-user-tag"}, 
        {"heading": "Shop Management"},
        {"app": "products", "icon": "fas fa-leaf"},
        {"app": "orders", "icon": "fas fa-shopping-cart"},
        {"app": "employees", "icon": "fas fa-briefcase"},
        {"app": "farmers", "icon": "fas fa-tractor"},
        {"app": "businesses", "icon": "fas fa-building"},
        {"app": "finance", "icon": "fas fa-file-invoice-dollar"}, # <--- NEW: Jazzmin icon for finance app
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "show_ui_builder": DEBUG,
    "order_with_respect_to": ["auth", "users", "products", "orders", "employees", "farmers", "businesses", "finance"], # <--- NEW: Add finance to order
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.CustomUser": "fas fa-user-circle",
        "users.OneTimePassword": "fas fa-key",
        "products.Product": "fas fa-apple-alt",
        "products.Category": "fas fa-tags",
        "orders.Order": "fas fa-box",
        "orders.OrderItem": "fas fa-box-open",
        "employees.Employee": "fas fa-id-badge",
        "farmers.Farmer": "fas fa-seedling",
        "businesses.Business": "fas fa-city",
        "dashboards.Dashboard": "fas fa-chart-line",
        "finance.FarmerBill": "fas fa-file-invoice", # <--- NEW: Icon for FarmerBill model
    },
    "related_modal_active": False 
}

JAZZMIN_UI_SETTINGS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "navbar_fixed": True,
    "navbar_links_left": [], 
    "navbar_links_right": [],
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "sidebar_show_quick_panel": False,
    "sidebar_show_tooltips": True,
    "sidebar_search": True,
    "show_breadcrumbs": True,
    "site_width": "full",
    "site_brand": "Farm Shop",
    "site_brand_header_link": "/",
    "welcome_text_header": "Farm Shop Admin",
    "topbar_brand_text": "Farm Shop",
    "custom_css": None,
    "custom_js": None,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'apps.users.views': { # Target the logger specifically in your views.py
            'handlers': ['console'],
            'level': 'DEBUG', # Always show DEBUG messages from your custom views
            'propagate': False,
        },
    },
}